import Head from "next/head";
import WebLayout from "../layouts/WebLayout";
import { useSelector } from "react-redux";
// import axios from "../config/axios.config";
import axios from "axios";

const Home = () => {
	const userInfo = useSelector((state) => state.auth);
	const { user } = userInfo;

	return (
		<WebLayout>
			<Head>
				<title>Bloggers | Home</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h2 className="text-2xl font-semibold text-green-600">Hello</h2>
		</WebLayout>
	);
};

export default Home;
