import Head from "next/head";
import Image from "next/image";

const Home = () => {
	return (
		<div>
			<Head>
				<title>Bloggers | Home</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h2 className="text-2xl font-semibold text-green-600">Hello</h2>
		</div>
	);
};

export default Home;
