import Head from "next/head";
import React, { useEffect, useState } from "react";
import AuthLayout from "../layouts/AuthLayout";
import { useDispatch, useSelector } from "react-redux";
import { loginUser } from "../redux/actions/authActions";
import RotateLoader from "react-spinners/RotateLoader";
import Link from "next/link";
import { useRouter } from "next/router";

const Login = () => {
	const router = useRouter();
	const [email, setEmail] = useState("");
	const [password, setPassword] = useState("");
	const [errMsg, setErrMsg] = useState(null);
	const dispatch = useDispatch();
	const userLogin = useSelector((state) => state.auth);
	const { loading, error, userInfo } = userLogin;

	const handleSubmit = (e) => {
		e.preventDefault();

		dispatch(loginUser(email, password));
		setEmail("");
		setPassword("");
	};

	const handleError = (msg) => {
		setErrMsg(msg);

		setTimeout(() => {
			setErrMsg(null);
		}, 5000);
	};

	useEffect(() => {
		if (userInfo && !error && !loading) {
			router.push("/");
		}
	}, [userInfo, error, loading]);

	useEffect(() => {
		if (error) {
			handleError(error);
		}
	}, [error]);

	return (
		<AuthLayout>
			<Head>
				<title>Bloggers | Login</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="h-full flex items-center justify-center">
				<div className="bg-green-700 min-w-[350px] w-[400px] lg:w-[450px] mt-10 lg:mt-20 rounded-lg p-5">
					<h2 className="text-white font-semibold text-center text-3xl">
						Login
					</h2>

					{errMsg && (
						<div className="bg-red-100 w-full text-center mt-5 py-2 border-2 border-red-500 rounded-lg">
							<h2 className="text-red-600 font-semibold text-base">
								{errMsg}
							</h2>
						</div>
					)}

					<form className="space-y-6 my-5" onSubmit={handleSubmit}>
						<div className="">
							<input
								type="text"
								className="w-full h-[45px] rounded-lg outline-none border-2 border-green-700 pl-2 font-medium leading-5 text-lg"
								value={email}
								onChange={(e) => setEmail(e.target.value)}
								placeholder="Enter your email address"
							/>
						</div>
						<div className="">
							<input
								type="password"
								className="w-full h-[45px] rounded-lg outline-none border-2 border-green-700 pl-2 font-medium leading-5 text-lg"
								value={password}
								placeholder="Enter your password"
								onChange={(e) => setPassword(e.target.value)}
							/>
						</div>
						<button
							type="submit"
							className="bg-white w-full rounded-lg h-[45px] font-medium  text-green-700 text-lg"
						>
							{!loading && <h2>Submit</h2>}
							{loading && <RotateLoader size={24} />}
						</button>
					</form>

					<div className="w-full text-center">
						<Link href="/register">
							<a className="text-white text-center">
								Don't have an account? Click here.
							</a>
						</Link>
					</div>
				</div>
			</div>
		</AuthLayout>
	);
};

export default Login;
