import Head from "next/head";
import React from "react";

const Login = () => {
	return (
		<div>
			<Head>
				<title>Bloggers | Login</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
		</div>
	);
};

export default Login;
